packages:
  - apps/*
  - packages/*
  - packages/integrations/*
  - tooling/*

catalog:
  "@orpc/server": 1.3.0
  "@orpc/client": 1.3.0
  "@orpc/openapi": 1.3.0
  "@orpc/contract": 1.3.0
  "@orpc/zod": 1.3.0
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.25.7
  dotenv-cli: ^7.4.2
  "@t3-oss/env-core": ^0.13.6
  hono: ^4.6.9
  "svelte": ^5.33.0
  "@sveltejs/kit": ^2.21.1
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@sveltejs/adapter-auto": ^4.0.0
  "@sveltejs/adapter-node": ^5.2.9
  "@sveltejs/enhanced-img": ^0.4.1
  "svelte-check": ^4.0.0
  "mdsvex": ^0.12.6
  "svelte-seo": ^1.6.1
  "bits-ui": "2.3.0"
  "@date-fns/tz": ^1.2.0
  "@lucide/svelte": ^0.511.0
  vite: ^6.3.5
  vitest: ^3.1.4
  "rrule-rust": 2.1.0-alpha.6
  pino: 9.6.0
  pino-pretty: 13.0.0
  hono-pino: 0.7.2
  "@opentelemetry/sdk-node": 0.57.2
  "@opentelemetry/sdk-logs": 0.57.2
  "@opentelemetry/sdk-metrics": 1.30.1
  "@opentelemetry/sdk-trace-base": 1.30.1
  "@opentelemetry/api": 1.9.0
  "@opentelemetry/api-logs": 0.57.2
  "@opentelemetry/instrumentation-pino": 0.46.1
  "@opentelemetry/instrumentation-http": 0.57.2
  "@opentelemetry/auto-instrumentations-node": 0.56.0
  "@opentelemetry/exporter-metrics-otlp-http": 0.57.2
  "@opentelemetry/exporter-metrics-otlp-proto": 0.57.2
  "@opentelemetry/exporter-trace-otlp-http": 0.57.2
  "@biomejs/biome": "1.9.4"
  nanoid: 5.1.5
  "@testcontainers/postgresql": 10.27.0
  testcontainers: 10.27.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
