import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  installationSidebar: [
    {
      type: "autogenerated",
      dirName: "introduction",
    },
  ],
  integrationsSidebar: [
    "integrations/index",
    {
      type: "category",
      label: "All integrations",
      items: [
        "integrations/google-calendar",
        "integrations/linear",
        "integrations/google-people",
      ],
    },
    {
      type: "category",
      label: "Events",
      items: ["integrations/google-calendar"],
    },
    {
      type: "category",
      label: "Tasks",
      items: ["integrations/linear"],
    },
    {
      type: "category",
      label: "People",
      items: ["integrations/linear", "integrations/google-people"],
    },
  ],
  apiSidebar: ["api/index"],
};

export default sidebars;
