name: Release Canary

on:
  pull_request:
    types: [labeled]
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: contains(github.event.pull_request.labels.*.name, 'release canary')
    timeout-minutes: 10
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build And Check Packages
        run: pnpm build

      # pkg-pr-new does not support prepublish, since it does "npm pack"
      - name: Prepublishing
        run: pnpm -F cli prepublish

      - name: Create pkg.pr.new build
        run: pnpm dlx pkg-pr-new publish --comment=create ./apps/mcp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: TODO: Send a Discord notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
