name: Upload Sourcemaps to Sentry

on:
  workflow_run:
    workflows: ["Build and Publish Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  upload-sourcemaps-account:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build and upload sourcemaps for account
        working-directory: apps/account
        env:
          CI: 1
          SENTRY_AUTH_TOKEN: ${{ secrets.INFISICAL_SENTRY__SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.INFISICAL_SENTRY__SENTRY_ORG }}
          SENTRY_PROJECT: account-sveltekit
        run: pnpm build

  upload-sourcemaps-landing:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build and upload sourcemaps for landing
        working-directory: apps/landing
        env:
          CI: 1
          SENTRY_AUTH_TOKEN: ${{ secrets.INFISICAL_SENTRY__SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.INFISICAL_SENTRY__SENTRY_ORG }}
          SENTRY_PROJECT: landing-sveltekit
        run: pnpm build

  upload-sourcemaps-authenticator:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build and upload sourcemaps for authenticator
        working-directory: apps/authenticator
        env:
          CI: 1
          SENTRY_AUTH_TOKEN: ${{ secrets.INFISICAL_SENTRY__SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.INFISICAL_SENTRY__SENTRY_ORG }}
          SENTRY_PROJECT: authenticator-sveltekit
        run: pnpm build

  upload-sourcemaps-developers:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build and upload sourcemaps for developers
        working-directory: apps/developers
        env:
          CI: 1
          SENTRY_AUTH_TOKEN: ${{ secrets.INFISICAL_SENTRY__SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.INFISICAL_SENTRY__SENTRY_ORG }}
          SENTRY_PROJECT: developers-sveltekit
        run: pnpm build
